spring:
  application:
    name: demo-payment-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
logging:
  level:
    web: DEBUG
paypal:
  mode: sandbox
  redirect:
    return: ${PAYMENT_REVIEW_URL}
    cancel: http://localhost:8080/paypal/payment/cancellation
    success: http://localhost:3000/courses/checkout/success
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
